blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from . import views


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", PostListView.as_view(), name='blog-home'),
     path("user/<str:username>", UserPostListView.as_view(), name='user-post'),
    path("post/<int:pk>/", PostDetailView.as_view(), name='post_detail'),
    path("post/new/", PostCreateView.as_view(), name='post_create'),
    path("post/<int:pk>/update", PostUpdateView.as_view(), name='post_update'),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name='post_delete'),
    path("about/", views.about, name='blog-about')
]

## naming convention of template file the browser is looking for
## <app>/<model>_<viewtype>.html 

core/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blog.urls')),
    path("users/",include('users.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name= 'users'

urlpatterns=[
    path('register/', views.RegisterView, name='register'),
    path('profile/', views.ProfileView, name='profile'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.LogoutView, name='logout'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title= models.CharField(max_length=100)
    content= models.TextField()
    date_posted= models.DateTimeField(default=timezone.now)
    author= models.ForeignKey(User, on_delete= models.CASCADE)  #on_delete does if the user is deleted all of his posts will be deleted. But if you delete the psot the user will not be deleted

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post_detail' , kwargs={'pk': self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)     
    image = models.ImageField(default='default.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img= Image.open(self.image.path)
        if img.height >300 or img.width >300:
            output_size=(300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegistrationForm (UserCreationForm):
    email= forms.EmailField()

    class Meta:     # Class meta gives us a nested namespace for configurations and keeps the configurations at one place and within the configuration we're saying that the model will be affected if the user model. the fields that are listed are the fields that we want in the foem and in one order 
        model = User
        fields= ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email= forms.EmailField()
    class Meta:
        model= User
        fields= ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model= Profile
        fields= ['image'] 

blog/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from .models import *

# Create your views here.
posts=[
    {
        'author':'Khalil',
        'title': 'Therefore, I am',
        'content':'Do it your self',
        'date_posted': 'Sep-9,2023'
    }
]
def home(request):
    context={
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

class PostListView(ListView):
    model= Post
    template_name= 'blog/home.html'  ## <app>/<model>_<viewtype>.html 
    context_object_name= 'posts'
    ordering= ['-date_posted']

class UserPostListView(ListView):
    model= Post
    template_name= 'blog/user_posts.html'  ## <app>/<model>_<viewtype>.html 
    context_object_name= 'posts'
    # ordering= ['-date_posted']

    def get_queryset(self):
        user= get_object_or_404(User,username= self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model= Post
    
class PostCreateView(LoginRequiredMixin,CreateView):
    model= Post
    fields= ['title', 'content']
    success_url= reverse_lazy('blog-home')

    def form_valid(self, form):
        form.instance.author= self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model= Post
    fields= ['title', 'content']
    # success_url= 'blog/home.html'

    def form_valid(self, form):
        form.instance.author= self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post= self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model= Post
    success_url= '/'

    def test_func(self):
        post= self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile

# Create your views here.
def RegisterView(request):
    if request.method == 'POST':
        form= UserRegistrationForm(request.POST)
        if form.is_valid():
            # form.save()
            user = form.save()
            profile = Profile(user=user)
            profile.save()
            login(request, user)
            username= form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created. You can now login!')
            # Create a profile for the user
            # profile = Profile(user=user)
            # profile.save()
            return redirect ('users:login')
            # return redirect('blog:blog-home')
    else:
        form= UserRegistrationForm()
    return render(request, 'users/register.html', {'form':form})

def LoginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login (request, user)
            return redirect ('blog-home')
    else:
        form = AuthenticationForm()
    return render (request, 'users/login.html', {'form':form})

def LogoutView(request):
    logout(request)
    return render(request, 'users/logout.html')

@login_required
def ProfileView(request):
    if request.method == 'POST':
        user_form= UserUpdateForm(request.POST, instance=request.user)
        profile_form= ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f'Your account has been Updated.!')
            return redirect ('users:profile')
    else: 
        user_form= UserUpdateForm()
        profile_form= ProfileUpdateForm()
    context={ 
        'user_form':user_form,
        'profile_form': profile_form
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>Want to know about us</h1>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'post_create' %}">New Post</a>
                            <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                </div>
            </div>
        </div>
    </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages%}
                        <div class="alert alert-{{message.tags}}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif%}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {%for post in posts%}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
</article>
    {%endfor%}
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{object.title}}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post_detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %} 

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{object.author.profile.image.url}}" >
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-post' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post_update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post_delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>
 
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h2 class="mb-3">Posts by {{view.kwargs.username}}</h2>
    {%for post in posts%}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{post.author.profile.image.url}}" >
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-post' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {%endfor%}
{% endblock %}  

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div> 
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            {% comment %} user.profile.image.url {% endcomment %}
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}